package com.kjh.aps.persistent;

import java.util.List;
import java.util.Map;

import com.kjh.aps.domain.BoardDTO;
import com.kjh.aps.domain.BroadcasterDTO;
import com.kjh.aps.domain.CommentDTO;
import com.kjh.aps.domain.CommentReplyDTO;
import com.kjh.aps.domain.ReviewGradePointDTO;

public interface CommunityDAO {
	public List<BroadcasterDTO> selectBroadcasterList(String type) throws Exception;
	public List<BroadcasterDTO> selectBroadcasterByMap(Map<String, String> map) throws Exception;
	public List<BoardDTO> selectBoardWriteListByMap(Map<String, String> map) throws Exception;
	public BroadcasterDTO selectBroadcasterById(String id) throws Exception;
	public int insertBoardWrite(BoardDTO dto) throws Exception;
	public BoardDTO selectBoardWriteByMap(Map<String, String> map) throws Exception;
	public int selectBoardWriteCountByMap(Map<String, String> map) throws Exception;
	public List<BoardDTO> selectSearchBoardListByMap(Map<String, String> map) throws Exception;
	public int selectSearchBoardCountByMap(Map<String, String> map) throws Exception;
	public int updateBoardWrite(BoardDTO dto) throws Exception;
	public int selectBoardWriteUserIdByMap(Map<String, String> map) throws Exception;
	public int deleteBoardWrite(Map<String, String> map) throws Exception;
	public int updateBoardWriteView(Map<String, String> map) throws Exception;
	public Integer selectBoardWriteRecommendHistoryTypeByMap(Map<String, String> map) throws Exception;
	public int updateBoardWriteRecommend(Map<String, String> map) throws Exception;
	public int insertBoardWriteRecommendHistory(Map<String, String> map) throws Exception;
	public int insertBoardWriteComment(CommentDTO dto) throws Exception;
	public List<CommentDTO> selectBoardWriteCommentListByMap(Map<String, String> map) throws Exception;
	public int selectBoardWriteCommentCountByMap(Map<String, String> map) throws Exception;
	public int insertBoardWriteCommentReply(CommentReplyDTO dto) throws Exception;
	public List<CommentReplyDTO> selectBoardWriteCommentReplyListByMap(Map<String, Integer> map) throws Exception;
	public int selectBoardWriteCommentReplyCountByBoardCommentId(int id) throws Exception;
	public CommentDTO selectBoardWriteCommentByMap(Map<String, Integer> map) throws Exception;
	public int updateBoardWriteComment(CommentDTO dto) throws Exception;
	public int deleteBoardWriteComment(Map<String, Integer> map) throws Exception;
	public Integer selectBoardWriteCommentUserIdByMap(Map<String, Integer> map) throws Exception;
	public Integer selectBoardWriteCommentReplyUserIdByMap(Map<String, Integer> map) throws Exception;
	public int deleteBoardWriteCommentReply(Map<String, Integer> map) throws Exception;
	public Integer selectBoardWriteCommentRecommendHistoryTypeByMap(Map<String, String> map) throws Exception;
	public int updateBoardWriteCommentRecommend(Map<String, String> map) throws Exception;
	public int insertBoardWriteCommentRecommendHistory(Map<String, String> map) throws Exception;
	public int insertBroadcasterReview(CommentDTO dto) throws Exception;
	public List<CommentDTO> selectBroadcasterReviewListByMap(Map<String, String> map) throws Exception;
	public int selectBroadcasterReviewListCountByMap(Map<String, String> map) throws Exception;
	public int insertBroadcasterReviewReply(CommentReplyDTO dto) throws Exception;
	public List<CommentReplyDTO> selectBroadcasterReviewReplyListByMap(Map<String, Integer> map) throws Exception;
	public int selectBroadcasterReviewReplyCountByBroadcasterReviewId(int id) throws Exception;
	public CommentDTO selectBroadcasterReviewByMap(Map<String, String> map) throws Exception;
	public int updateBroadcasterReview(CommentDTO dto) throws Exception;
	public int deleteBroadcasterReview(Map<String, String> map) throws Exception;
	public int deleteBroadcasterReviewReply(Map<String, Integer> map) throws Exception;
	public Integer selectBroadcasterReviewRecommendHistoryTypeByMap(Map<String, String> map) throws Exception;
	public int insertBroadcasterReviewRecommendHistory(Map<String, String> map) throws Exception;
	public int updateBroadcasterReviewRecommend(Map<String, String> map) throws Exception;
	public int selectBroadcasterReviewCount(Map<String, String> map) throws Exception;
	public List<ReviewGradePointDTO> selectBroadcasterReviewGradePointAverageListByMap(Map<String, String> map) throws Exception;
	public ReviewGradePointDTO selectBroadcasterReviewGradePointAverageByMap(Map<String, String> map) throws Exception;
	public int selectBroadcasterReviewCountByMap(Map<String, String> map) throws Exception;
	public List<BoardDTO> selectLastNotice() throws Exception;
	public List<BoardDTO> selectCombineBoardWriteListByMap(Map<String, String> map) throws Exception;
	public int selectCombineBoardWriteCountByMap(Map<String, String> map) throws Exception;
	public BoardDTO selectCombineBoardWriteByMap(Map<String, String> map) throws Exception;
	public String selectCombineBoardWriteTypeById(int id) throws Exception;
	public int updateCombineBoardWriteView(Map<String, String> map) throws Exception;
	public BoardDTO selectModifyCombineBoardWriteByMap(Map<String, String> map) throws Exception;
	public int updateCombineBoardWrite(BoardDTO dto) throws Exception;
	public int updateCombineBoardWriteRecommend(Map<String, String> map) throws Exception;
	public Integer selectCombineBoardWriteRecommendHistoryTypeByMap(Map<String, String> map) throws Exception;
	public int insertCombineBoardWriteRecommendHistory(Map<String, String> map) throws Exception;
	public int deleteCombineBoardWrite(Map<String, String> map) throws Exception;
	public int insertCombineBoardWriteComment(CommentDTO dto) throws Exception;
	public List<CommentDTO> selectCombineBoardWriteCommentListByMap(Map<String, String> map) throws Exception;
	public int selectCombineBoardWriteCommentCountByMap(Map<String, String> map) throws Exception;
	public String selectCombineBoardWriteCommentTypeById(int id) throws Exception;
	public CommentDTO selectCombineBoardWriteCommentByMap(Map<String, String> map) throws Exception;
	public int updateCombineBoardWriteComment(CommentDTO dto) throws Exception;
	public int deleteCombineBoardWriteComment(Map<String, String> map) throws Exception;
	public int updateCombineBoardWriteCommentRecommend(Map<String, String> map) throws Exception;
	public Integer selectCombineBoardWriteCommentRecommendHistoryTypeByMap(Map<String, String> map) throws Exception;
	public int insertCombineBoardWriteCommentRecommendHistory(Map<String, String> map) throws Exception;
	public int insertCombineBoardWriteCommentReply(CommentReplyDTO dto) throws Exception;
	public List<CommentReplyDTO> selectCombineBoardWriteCommentReplyListByMap(Map<String, Integer> map) throws Exception;
	public int selectCombineBoardWriteCommentReplyCountByCombineBoardCommentId(int id) throws Exception;
	public String selectCombineBoardWriteCommentReplyTypeById(int id) throws Exception;
	public int deleteCombineBoardWriteCommentReply(Map<String, String> map) throws Exception;
	public List<BoardDTO> selectSearchCombineBoardWriteListByMap(Map<String, String> map) throws Exception;
	public int selectSearchCombineBoardWriteCountByMap(Map<String, String> map) throws Exception;
}