package com.kjh.aps.persistent;

import java.util.List;
import java.util.Map;

import com.kjh.aps.domain.UserPushDTO;

public interface CommonDAO {
	public int insertUserPush(UserPushDTO dto) throws Exception;
	public int selectUserIdByUserPushDTO(UserPushDTO dto) throws Exception;
	public List<UserPushDTO> selectUserPushListByUserId(int userId) throws Exception;
	public int updateUserPushStatus(Map<String, Integer> map) throws Exception;
	public int deleteUserPush(Map<String, String> map) throws Exception;
	public Map<String, Integer> selectUserRecommendCountByMap(Map<String, String> map) throws Exception;
	public int updateUserLevel(Map<String, String> map) throws Exception;
	public int deleteExpireBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireBoardWriteRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBoardWrite(int expireDay) throws Exception;
	public int deleteExpireUserLog(int expireDay) throws Exception;
	public int deleteExpireUserBan(int expireDay) throws Exception;
	public int deleteExpireUserPush(int expireDay) throws Exception;
	public int deleteExpireUser(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteCommentChildReply(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteChildRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserBoardWriteRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserBoardWrite(int expireDay) throws Exception;
	public int deleteExpireBoardWriteCommentIndivReply(int expireDay) throws Exception;
	public int deleteExpireBoardWriteCommentIndivRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBoardWriteCommentIndiv(int expireDay) throws Exception;
	public int deleteExpireBoardWriteCommentReplyIndiv(int expireDay) throws Exception;
	public int deleteExpireBraodcasterReviewIndivReply(int expireDay) throws Exception;
	public int deleteExpireBraodcasterReviewIndivRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBraodcasterReviewIndiv(int expireDay) throws Exception;
	public int deleteExpireBraodcasterReviewReplyIndiv(int expireDay) throws Exception;
	public int deleteExpireUserBroadcasterReviewChildReply(int expireDay) throws Exception;
	public int deleteExpireUserBroadcasterReviewReply(int expireDay) throws Exception;
	public int deleteExpireUserBroadcasterReviewChildRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserBroadcasterReviewRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserBroadcasterReview(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWrite(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentIndivReply(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentReplyIndiv(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentIndivRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceBoardWriteCommentIndiv(int expireDay) throws Exception;
	public int deleteExpireUserCustomerServiceBoardWriteCommentChildReply(int expireDay) throws Exception;
	public int deleteExpireUserCustomerServiceBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireUserCustomerServiceBoardWriteCommentChildRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserCustomerServiceBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserCustomerServiceBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireBroadcasterBoardWriteRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBroadcasterBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireBroadcasterReviewRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCustomerServiceCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserPushIndiv(int expireDay) throws Exception;
	public int deleteSuspensionExpireUser() throws Exception;
	public int updateSuspensionExpireUser() throws Exception;
	public int deleteExpireCombineBoardWriteRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentRecommendHistoryIndiv(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteRecommendHistoryIndiv(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWrite(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteCommentChildReply(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteCommentReply(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteCommentRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteComment(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteChildRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWriteRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireUserCombineBoardWrite(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentIndivReply(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentReplyIndiv(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentIndivRecommendHistory(int expireDay) throws Exception;
	public int deleteExpireCombineBoardWriteCommentIndiv(int expireDay) throws Exception;
}